MediaArea/MediaConch_SourceCode

Source/Common/Policies.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/policiesedit.cpp, Source/GUI/Qt/policiesedit.h, Source/GUI/Qt/policiesedit.ui, Source/GUI/Qt/policiesmenu.cpp, Source/GUI/Qt/policiesmenu.ui
=> Policies cleaning

Source/GUI/Qt/policiesedit.cpp, Source/GUI/Qt/policiesedit.h, Source/GUI/Qt/policiesedit.ui
=> Policies: Edit rules on the fly

Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/policiesedit.cpp, Source/GUI/Qt/policiesedit.h
=> Policies: Edit the rule name automatically

Source/CLI/CLI_Main.cpp, Source/CLI/CommandLine_Parser.cpp, Source/Common/Core.cpp
=> Schematron: allow to validate with multiple schematron files

Project/GNU/CLI/.gitignore, Project/Qt/.gitignore
=> Mediaconch: add simple gitignore

Project/GNU/CLI/Makefile.am, Source/CLI/CommandLine_Parser.cpp, Source/CLI/Help.cpp, Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/JS_Tree.cpp, Source/Common/JS_Tree.h
=> JS_Tree: send json from xml with JS Tree format

Source/CLI/CommandLine_Parser.cpp, Source/CLI/CommandLine_Parser.h, Source/CLI/Help.cpp, Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/Schema.cpp, Source/Common/Schema.h, Source/Common/Schematron.cpp, Source/Common/Schematron.h, Source/Common/Xslt.cpp, Source/Common/Xslt.h, Source/GUI/Qt/WebPage.cpp, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/Resource/html/formOnline.html, Source/Resource/html/formRepository.html, Source/Resource/html/formUpload.html
=> Xslt: add option to modify the XSLT report output

Project/Qt/MediaConch.pro, Source/GUI/Qt/helpwindow.cpp, Source/GUI/Qt/helpwindow.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/mainwindow.ui, Source/Resource/Resources.qrc, Source/Resource/html/Help/Getting Started/Getting Started.html
=> GUI/Qt: add a more common help

Source/Common/XsltPolicy.h
=> Policy/XSLT: use class instead of struct

Source/GUI/Qt/checkerwindow.cpp
=> GUI/Qt: implementation report is really valid

Source/Common/XsltPolicy.cpp, Source/Common/XsltPolicy.h
=> Policy/XSLT: remove useless xslt parameter due to last update

Source/Resource/Resources.qrc, Source/Resource/html/base.html, Source/Resource/html/css/main.css, Source/Resource/html/fileDetailChecker.html, Source/Resource/html/js/jstreegrid.js
=> GUI/Qt/Web: use JS-Tree-Grid instead of JS-tree

Source/Resource/html/fileDetailChecker.html
=> GUI/Qt: change default report name for implementation report

Source/GUI/Qt/mainwindow.cpp
=> GUI/Qt: avoid to resize with the default window

Source/Resource/policies/General_Conformance.xsl, Source/Resource/policies/Standards_Mismatch_NTSC.xsl, Source/Resource/policies/Standards_Mismatch_PAL.xsl, Source/Resource/policies/Testing_Multiple_Files.xsl
=> Policy: update default policies

Source/Common/Core.cpp
=> ImplementationReport: use the correct detail level

Source/GUI/Qt/WebPage.cpp
=> GUI/Qt: HTML encoding problem

Source/Common/XsltPolicy.cpp
=> Polixy/XSLT: make occurrence optional in input

Source/Resource/html/fileDetailChecker.html
=> Open all nodes by default for MediaInfo jstree

Source/GUI/Qt/checkerwindow.cpp
=> GUI/QT/Web: add system or user policies/displays group

Source/CLI/CommandLine_Parser.cpp, Source/CLI/Help.cpp
=> CLI: use -v for version

README.md
=> Add travis status in README.md

Source/GUI/Qt/menumainwindow.cpp
=> x Fix Conch emoji display in the header with qt4

License.html
=> Update third party libraries licenses

README.md
=> x Ubuntu 15.10 is now supported

Project/GNU/CLI/configure.ac, Project/Qt/MediaConch.pro, Project/Qt/prepare
=> + sqlite and libevent for the GUI, with help from tribouille

Project/GNU/mediaconch.spec
=> Fix spec file to build with libevent on fedora

Project/GNU/CLI/Makefile.am, Project/GNU/CLI/configure.ac, Project/GNU/Daemon/Makefile.am, Project/GNU/Daemon/configure.ac
=> Remove some autotools warnings

Source/Common/Core.cpp, Source/GUI/Qt/mainwindow.cpp
=> Display: apply the display on invalid file

Source/CLI/CLI.cpp, Source/CLI/CLI.h, Source/CLI/CLI_Main.cpp
=> CLI: adapt command line for Unicode input

Source/Common/Core.cpp
=> change infinite loop kind

Source/GUI/Qt/xsltruleedit.cpp, Source/GUI/Qt/xsltruleedit.h
=> GUI/Policy/XSL: Do not reset field when updating selector

Source/Resource/displays/MediaConchHtml.xsl
@tribouille We can also have the CSS live in a separate location. Let me know what's best for you (in this PR or via email).
=> updates mediaconch html and adds stylesheet details into template

Source/GUI/Qt/policieswindow.cpp
=> GUI: Do not delete 2 times the same policy

Source/Common/Policy.cpp, Source/GUI/Qt/policieswindow.cpp, Source/GUI/Qt/policieswindow.h, Source/GUI/Qt/schematronwindow.cpp, Source/GUI/Qt/xsltwindow.cpp
=> GUI: bold policies not saved

Source/Resource/Image/MediaConch.svg
=> Icon: resize MediaConch.svg

Source/Resource/html/fileDetailChecker.html, Source/Resource/html/js/jstreegrid.js
=> Fix column resize with jstree-grid

Project/Mac/Make_MC_dmg.sh
=> x Little oversight in Make_MC_dmg.sh

Source/Common/JS_Tree.cpp, Source/Common/JS_Tree.h
=> JS-TREE: unified output JSON

Project/GNU/mediaconch.spec
=> x Correct the macro problem in the .spec

Source/Daemon/Daemon.cpp, Source/Daemon/Daemon.h, Source/Daemon/Help.cpp
=> Daemon: use schema for validation implementation

License.html
=> Update License.html file

Source/Common/SQLLite.cpp
=> SQLITE: return the correct type

Source/GUI/Qt/WebKitPage.cpp
=> Qt/WebKit: fix the download report buttons

Source/Common/LibEventHttpd.cpp, Source/Common/REST_API.cpp, Source/Common/REST_API.h, Source/Daemon/Daemon.cpp, Source/Daemon/Daemon.h, Source/Daemon/Help.cpp
=> Daemon: add log when event happen

Documentation/REST.md
=> REST API documentation small fixes

Documentation/Config.md, Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/Database.cpp, Source/Common/Database.h, Source/Common/MediaConchLib.cpp, Source/Common/MediaConchLib.h, Source/Common/NoDatabase.cpp, Source/Common/NoDatabase.h, Source/Common/SQLLite.cpp, Source/Common/SQLLite.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h
=> GUI: introduce the database to remember the files used

Documentation/REST.md, Source/Common/Core.h, Source/Common/DaemonClient.cpp, Source/Common/DaemonClient.h, Source/Common/Http.cpp, Source/Common/Http.h, Source/Common/Httpd.cpp, Source/Common/Httpd.h, Source/Common/LibEventHttpd.cpp, Source/Common/MediaConchLib.cpp, Source/Common/MediaConchLib.h, Source/Common/REST_API.cpp, Source/Common/REST_API.h, Source/Daemon/Daemon.cpp, Source/Daemon/Daemon.h
=> API: Create command file_from_id

Source/GUI/Qt/WebEnginePage.cpp, Source/GUI/Qt/WebKitPage.cpp, Source/GUI/Qt/mainwindow.h, Source/Resource/html/menu.html
=> GUI: add help to the menu

Source/CLI/CLI.cpp, Source/CLI/CLI.h, Source/CLI/CommandLine_Parser.cpp, Source/CLI/CommandLine_Parser.h, Source/CLI/Help.cpp
=> CLI: make sync by default, add option to be asynchronous

Source/Common/REST_API.cpp, Source/Daemon/Daemon.cpp
=> Daemon/Validate: init the validate report if different from implem

Source/GUI/Qt/WebEnginePage.cpp, Source/GUI/Qt/WebEnginePage.h, Source/GUI/Qt/WebKitPage.cpp, Source/GUI/Qt/WebKitPage.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/resultwindow.cpp, Source/GUI/Qt/resultwindow.h
=> GUI: update webpage in another thread

Source/GUI/Qt/WebEnginePage.cpp, Source/GUI/Qt/WebKitPage.cpp, Source/GUI/Qt/resultwindow.cpp, Source/GUI/Qt/workerfiles.cpp
=> GUI: adapt labels for analyze state

Source/Resource/policies/CAVPP_Access_Video_Files.xsl, Source/Resource/policies/CAVPP_Preservation_Video_Files.xsl
=> add cavpp access and preservation policy sets as examples

Project/Qt/MediaConch.pro
=> Qt5: put the objects files to _Automated

Project/GNU/GUI/AddThisToRoot_GUI_compile.sh
=> Mac: activate sqlite and libevent

Documentation/REST.md
=> Minor documentation update for REST API

README.md
=> README : new dependancies and compile.sh for src*zip

Source/GUI/Qt/WebKitPage.cpp
=> GUI/Qt: display policy viewer for MC implementation report

Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/MediaConchLib.cpp, Source/Common/Queue.cpp, Source/Common/Queue.h, Source/Common/Scheduler.cpp, Source/Common/Scheduler.h
=> CLI: give the MIL options to MIL

Project/GNU/GUI/AddThisToRoot_GUI_compile.sh
=> Remove libcurl define

.travis.yml, Project/GNU/CLI/.gitignore, Project/GNU/CLI/Makefile.am, Project/GNU/CLI/test/simple.sh, Project/GNU/CLI/test/test_ffv1.sh, Project/GNU/CLI/test/utils.sh, Source/Resource/schema/MatroskaSchema.xml
=> Travis: Add some tests

Source/GUI/Qt/mainwindow.cpp
=> GUI/Policy: use UTF8 in report

Source/GUI/Qt/WebEnginePage.cpp, Source/GUI/Qt/WebKitPage.cpp, Source/GUI/Qt/mainwindow.cpp
=> GUI: fix the Open file

Source/GUI/Qt/mainwindow.cpp
=> GUI: change default display value

Source/GUI/Qt/WebEngineView.cpp, Source/GUI/Qt/WebEngineView.h, Source/GUI/Qt/WebKitView.cpp, Source/GUI/Qt/WebKitView.h
=> GUI: accepts drop in WUI

Source/GUI/Qt/WebEnginePage.cpp, Source/GUI/Qt/WebEnginePage.h, Source/GUI/Qt/WebKitPage.cpp, Source/GUI/Qt/WebKitPage.h
=> GUI: drag and drop files and directories possible

Project/GNU/mediaconch.spec
=> Add appdata xml to rpm packages

Project/Qt/MediaConch.pro, Source/GUI/Qt/DatabaseUi.cpp, Source/GUI/Qt/DatabaseUi.h, Source/GUI/Qt/NoDatabaseUi.cpp, Source/GUI/Qt/NoDatabaseUi.h, Source/GUI/Qt/SQLLiteUi.cpp, Source/GUI/Qt/SQLLiteUi.h, Source/GUI/Qt/displaywindow.cpp, Source/GUI/Qt/loaddisplaypathbox.cpp, Source/GUI/Qt/loaddisplaypathbox.h, Source/GUI/Qt/loadpolicypathbox.cpp, Source/GUI/Qt/loadpolicypathbox.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/mainwindow.ui, Source/GUI/Qt/savedisplaypathbox.cpp, Source/GUI/Qt/savedisplaypathbox.h, Source/GUI/Qt/savepolicypathbox.cpp, Source/GUI/Qt/savepolicypathbox.h, Source/GUI/Qt/uisettings.cpp, Source/GUI/Qt/uisettings.h
=> Settings: save the save/load policy/display path

Source/Common/Queue.cpp
=> Options: fix iterator begin

Source/GUI/Qt/WebEngineView.cpp, Source/GUI/Qt/WebKitView.cpp
=> GUI/Web: remove right click button

Source/Resource/html/js/checker.js
=> Fix js variable overlap

Source/Resource/html/js/checker.js
=> GUI/Web: check if policy different from -1

Source/Common/Core.cpp, Source/Common/DatabaseReport.cpp, Source/Common/DatabaseReport.h, Source/Common/SQLLiteReport.cpp, Source/Common/SQLLiteReport.h
=> DB: indicates if the MIL version is present to re-update the report

Source/Resource/displays/MediaConchHtml.xsl
=> Add a uniq ID for policy report toggle

Source/Common/JS_Tree.cpp
=> JS_TREE: print all extra data in MediaInfo report

Source/Common/XsltPolicy.cpp
=> Policy/XSLT: do not hard-code text for non correct node type

Source/Common/Scheduler.cpp
=> Queue: use MediaInfo for percent parsed

Source/CLI/Help.cpp
=> CLI: fix the help for compression abreviation

Source/Resource/displays/MediaConchHtml.xsl, Source/Resource/displays/MediaConchText.xsl, Source/Resource/displays/MediaConchTextUnicode.xsl
This updates the HTML display for repot-level toggling and test-level detail with arrows. No fancy CSS transformations yet.
=> updates to displays

Source/Resource/displays/MediaConchHtml.xsl
Attn @JeromeMartinez! This also corrects the title displaying even when empty.
=> Leaner HTML display

Source/Resource/html/css/main.css
=> Temporarily workaround for line height problem with webengine

.travis.yml
=> Travis: use the last release package for MIL

Release/Release_CLI_GNU_Prepare.bat, Release/Release_CLI_Windows_i386.bat, Release/Release_CLI_Windows_x64.bat, Release/Release_GUI_GNU_Prepare.bat, Release/Release_GUI_Windows.bat, Release/Release_GUI_Windows_i386.bat, Release/Release_GUI_Windows_x64.bat, Release/Release_Server_Windows_i386.bat, Release/Release_Server_Windows_x64.bat, Release/Release_Source.bat
=> Unify binaries search paths

Source/Resource/html/js/policy.js
=> WUI/Policies: fix WUI when deleting policy

Source/Common/NoDatabaseReport.cpp, Source/Common/NoDatabaseReport.h
+ adapt report kind for MicroMediaTrace
=> NoDatabaseReport: correct method interface with the new abstract class

Source/Resource/html/js/policy.js
=> Close info message when user click on another policy/rule

Project/GNU/mediaconch.dsc, Project/GNU/mediaconch.spec, debian/control, debian/rules
=> Add debug packages

Source/Resource/html/js/checker.js
=> WUI/Checker: remove node is not saved #369

Source/GUI/Qt/mainwindow.ui
=> GUI: add a ctrl-q shortcut to quit

Source/Common/Core.cpp
=> Core: encode the special chars in MI report

Project/Qt/MediaConch.pro, Project/Qt/prepare
=> MediaConch.pro check dependencies on system

Source/Resource/html/js/policyTree.js
=> WUI: fix something in rule edit

Project/Qt/MediaConch.pro
=> Fix build on Windows

Source/Resource/displays/MediaConchHtml.xsl
Ah, what I meant to send over this morning. 😅
=> updates for padding and displaying fail/pass

Project/GNU/CLI/Makefile.am, Project/GNU/CLI/test/filename.sh, Source/Common/Core.cpp
=> CLI: Add test for avoid filename handling regression

Source/CLI/CLI.cpp, Source/CLI/CommandLine_Parser.cpp, Source/Common/Core.cpp, Source/Common/MediaConchLib.cpp
=> CLI: add MicroMediaTrace option

Project/GNU/CLI/AddThisToRoot_CLI_compile.sh, Project/GNU/CLI/configure.ac, Project/GNU/GUI/AddThisToRoot_GUI_compile.sh, Project/GNU/Server/AddThisToRoot_Server_compile.sh, Project/GNU/Server/configure.ac, Project/Qt/MediaConch.pro
=> Configure all projects before build

Tools/Policies/sample_policy_1.xml
fix policy type, only test width once
=> updates to ntsc pal policy

Source/Resource/displays/MediaConchText.xsl, Source/Resource/displays/MediaConchTextUnicode.xsl
=> updates if statements for name and description to for-each

Project/GNU/CLI/AddThisToRoot_CLI_compile.sh, Project/GNU/GUI/AddThisToRoot_GUI_compile.sh, Project/GNU/Server/AddThisToRoot_Server_compile.sh, Project/Qt/MediaConch.pro, README.md
=> Request static libs in build scripts

Tools/Transforms/verapdf2mediaconch.xsl
updates to verapdf version 0.24.2
=> update verapdf2mediaconch transform

Tools/Transforms/dpfmanager2mediaconch.xsl
=> dpfmanager2mediaconch update

Source/Resource/displays/MediaConchHtml.xsl, Source/Resource/displays/MediaConchText.xsl, Source/Resource/displays/MediaConchTextUnicode.xsl
Updates display to honor display compliance with PR #423, #422 -- and some minimal work towards #420 comparing.
=> Updates for veraPDF, DPFManager display, compare display

Source/CLI/CLI.cpp, Source/Common/MediaConchLib.cpp
Suggested-by: Dave Rice <dave@dericed.com>
=> CLI: change the output log for mmt without XML

Source/GUI/Qt/WebCommonPage.cpp
=> WUI: fix duplicate and policy show

Tools/Policies/sample_policy_7_memoriav_recommendations.xml
thx to @pjotrek-b. fixes
https://github.com/MediaArea/MediaConch/issues/152
=> fix policy typo

Source/Resource/html/js/publicPolicies/listPolicyTree.js, Source/Resource/html/xslPolicy.html
Fix https://github.com/MediaArea/MediaConch_SourceCode/issues/430
=> Show MediaTrace in the UI

Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/WebCommonPage.h, Source/Resource/html/js/checker.js, Source/Resource/html/js/policy.js
=> WUI: tooltip

Source/GUI/Qt/WebCommonPage.cpp
=> WUI: open tooltip using user browser

Source/Resource/html/publicPolicies.html
@dericed @ablwr any proposal for better wording?
=> Public Policies: welcome message

Source/GUI/Qt/WebKitPage.cpp
=> Qt5/WebKit: enable remote address

Source/Resource/html/js/policyTreeRulesMI.js, Source/Resource/html/js/policyTreeRulesMT.js, Source/Resource/html/xslPolicy.html
=> Merge "Exists" and "Must exist" policy rule validator ( #446 )

Source/Resource/html/css/main.css
=> Fix fields width in policy editor ( #447 )

Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/workerfiles.cpp, Source/Resource/html/js/checker.js
=> WUI: fix WebKit policy update js

Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/PluginsManager.cpp, Source/Common/PluginsManager.h, Source/Common/Queue.cpp, Source/Common/Scheduler.cpp, Source/Common/Scheduler.h
=> Log: add a debug log used by the bench tool

Source/GUI/Qt/WebKitPage.cpp
Signed-off-by: Florent Tribouilloy florent@mediaarea.net
=> WUI/WebKit: add inspector in debug mode

Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/WebCommonPage.h, Source/GUI/Qt/policieswindow.cpp, Source/Resource/Resources.qrc, Source/Resource/html/js/policy.js, Source/Resource/html/js/policyUser.js, Source/Resource/html/js/users/userWebEngine.js, Source/Resource/html/js/users/userWebKit.js, Source/Resource/html/xslPolicy.html
=> Allow users to import policies from their MediaConchOnline account

Project/AppImage/Recipe.sh
=> fix AppImage deps

Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/WebCommonPage.h, Source/GUI/Qt/workerfiles.cpp, Source/Resource/html/js/checker.js
=> WUI: fix error on status

Source/GUI/Qt/SQLLiteUi.cpp, Source/GUI/Qt/workerfiles.cpp, Source/Resource/html/js/checker.js
=> SQLite/UI: Add files per 50 to avoid too large query

Project/MSVC2013/GUI/MediaConch_GUI.vcxproj, Project/MSVC2013/GUI/MediaConch_GUI.vcxproj.filters, Project/MSVC2015/GUI/MediaConch_GUI.vcxproj, Project/MSVC2015/GUI/MediaConch_GUI.vcxproj.filters
=> Fix MSVC project files for commit d2bbd0f

Project/GNU/PKGBUILD
=> PKGBUILD: replace webengine by webkit

Source/CLI/CLI.cpp, Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/DaemonClient.cpp, Source/Common/DatabaseReport.cpp, Source/Common/DatabaseReport.h, Source/Common/MediaConchLib.h, Source/Common/NoDatabaseReport.cpp, Source/Common/NoDatabaseReport.h, Source/Common/REST_API.cpp, Source/Common/REST_API.h, Source/Common/SQLLiteReport.cpp, Source/Common/SQLLiteReport.h, Source/Common/Scheduler.cpp, Source/Common/WatchFolder.cpp, Source/Daemon/Daemon.cpp
=> Database/Report: Add multi-generated-ID

README.md
=> Add AppVeyor status to README.md

Documentation/Plugins.md, Source/Common/PluginPreHook.cpp, Source/Common/PluginPreHook.h, Source/Common/Queue.cpp, Source/Common/Scheduler.cpp, Source/Common/Scheduler.h, Source/Common/WatchFolder.cpp
=> Plugin: add multiple outputs to Pre Hook Plugins

Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/workerfiles.cpp
=> GUI: do not use separator on windows auto

Project/GNU/mediaconch.spec
=> rpm: Enable server on RHEL 7

Source/Resource/html/css/main.css, Source/Resource/html/js/publicPolicies/list.js
Close MediaArea/MediaConchOnline#79
=> Public policies: fix separation between blocks

Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/WebCommonPage.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/workerfiles.cpp, Source/GUI/Qt/workerfiles.h, Source/Resource/html/js/checker.js
=> WUI: add reload analyze button(force analyze)

Project/GNU/mediaconch.spec
=> Fix CentOS build

Project/GNU/CLI/AddThisToRoot_CLI_compile.sh, Project/GNU/GUI/AddThisToRoot_GUI_compile.sh, Project/GNU/Server/AddThisToRoot_Server_compile.sh
=> Compile external dependencies in *_FromSource packages

Project/GNU/CLI/AddThisToRoot_CLI_compile.sh, Project/GNU/GUI/AddThisToRoot_GUI_compile.sh, Project/GNU/Server/AddThisToRoot_Server_compile.sh, Project/Mac/BR_extension_CLI.sh, Project/Mac/BR_extension_GUI.sh, Project/Mac/BR_extension_Server.sh
+ libxml2 configuration from MediaConch README
+ remove unneeded cp
=> Fix build scripts

Source/Resource/html/css/main.css
=> Checker: reduce font size of jstree MediaInfo and MediaTrace

Source/Resource/html/js/checker.js
=> Checker: fix buttons alignment in the result table

Project/GNU/GUI/AddThisToRoot_GUI_compile.sh, Project/GNU/Server/AddThisToRoot_Server_compile.sh
=> Fix compilation order

History_CLI.txt, History_GUI.txt
=> Preparing v17.01.1

Source/Common/Core.cpp
Changed for mediainfo and mediatrace reports.
=> Fix incorrect namespaces in schemaLocation

Source/Resource/displays/MediaConchCSV.xsl
otherwise you can’t really test what the overall outcome was without
more info about how the policy is set up
=> add an overall result column to the csv

Tools/Policies/TN2162.xml
requires that
https://github.com/MediaArea/MediaConch_SourceCode/issues/538 is
resolved first
=> add policy to test for TN2162 rules

Project/Qt/MediaConch.pro, Source/GUI/Qt/WebCommonPage.cpp
=> Qt 4.6 compatibility

Source/CLI/CLI.cpp, Source/CLI/CLI.h, Source/Common/DaemonClient.cpp, Source/Common/MediaConchLib.cpp
=> CLI: do not need to force XML when using display

Project/GNU/GUI/mediaconch-gui.appdata.xml
=> Update AppData file

.travis.yml, Project/GNU/CLI/test/utils.sh
=> Travis: enable osx build

Source/Resource/html/css/main.css
=> Checker: update css file

Source/Resource/html/js/checker/cellStatus.js
=> Checker: fix display of status cell when file is reloaded

Source/Common/FileRegistered.h, Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/workerfiles.cpp, Source/GUI/Qt/workerfiles.h, Source/Resource/html/js/checker/base.js, Source/Resource/html/js/checker/table.js, Source/Resource/html/js/checker/webengine.js, Source/Resource/html/js/checker/webkit.js
=> GUI: add attachments process

Project/OBS/deb9.debian/control
=> Fix Zenlib version

Project/GNU/CLI/configure.ac, Source/CLI/CLI.cpp
=> Policy/path: use glob to get the real file name

Source/Common/Scheduler.cpp
=> Scheduler: name lookup of ‘i’ changed

Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/mainwindow.cpp
=> Use OS native dialogs

Source/GUI/Qt/settingswindow.cpp, Source/GUI/Qt/settingswindow.h, Source/Resource/html/js/settings.js, Source/Resource/html/settings.html
=> WUI: add a logged status in settings and forget button

Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/WebCommonPage.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/workerfiles.cpp, Source/GUI/Qt/workerfiles.h, Source/Resource/html/js/database/database.js, Source/Resource/html/js/database/databaseWebEngine.js, Source/Resource/html/js/database/databaseWebKit.js
=> WUI/Database: add a button to put again a file to the checker

Source/GUI/Qt/WebCommonPage.cpp
=> WUI: do not include \r to XML report

Source/Resource/html/js/checker/base.js
=> Restore fixer help button

Source/GUI/Qt/mainwindow.ui, Source/Resource/html/base.html
=> Temporarily disable new database page in GUI

.travis.yml, Project/GNU/CLI/Makefile.am, Project/GNU/CLI/test/test_mk.sh
=> Add mastroska implementations checks in testsuite

.travis.yml, Project/GNU/CLI/test/test_mk.sh
- MacOS compatibility
- Code rework
=> Update matroska checks

Project/GNU/mediaconch.spec
=> Mageia 6 and Fedora Rawhide support

Source/GUI/Qt/mainwindow.ui, Source/Resource/html/base.html, Source/Resource/html/css/main-gui.css, Source/Resource/html/database.html, Source/Resource/html/display.html, Source/Resource/html/js/database/database.js, Source/Resource/html/js/database/databaseWebEngine.js, Source/Resource/html/js/database/databaseWebKit.js
=> Use table view for the DB viewer

Source/Resource/displays/MediaConchSimple.xsl
=> only report reason if available

Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/MediaConchLib.cpp, Source/Common/MediaConchLib.h, Source/Common/Scheduler.cpp, Source/Common/Scheduler.h, Source/GUI/Qt/mainwindow.cpp
Can still be overridden by conf file.
=> GUI simultaneous thread settings set to "ideal thread count" by default.

.travis.yml, Project/GNU/CLI/test/test_mk.sh
=> tests: Generate and export TSV

Source/Common/Core.cpp
=> Ensure file is registered in the db when --Force is used

Source/CLI/CLI.cpp, Source/Common/MediaConchLib.cpp
=> Fix invalid combination of report/output

Project/Mac/Make_MC_xcarchive.sh
=> Fix iTunes archive generation

.travis.yml, Project/GNU/PKGBUILD, Project/GNU/mediaconch.spec, Project/OBS/deb9.debian/mediaconch-gui.install, Project/OBS/deb9.debian/rules
=> Qt5 on more distributions

Documentation/REST.md, Project/GNU/CLI/test/utils.sh, Source/CLI/CLI.cpp, Source/CLI/CLI.h, Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/DaemonClient.cpp, Source/Common/DaemonClient.h, Source/Common/Http.cpp, Source/Common/Http.h, Source/Common/Httpd.cpp, Source/Common/Httpd.h, Source/Common/LibEventHttpd.cpp, Source/Common/MediaConchLib.cpp, Source/Common/MediaConchLib.h, Source/Common/REST_API.cpp, Source/Common/REST_API.h, Source/Common/Reports.cpp, Source/Common/Reports.h, Source/Daemon/Daemon.cpp, Source/Daemon/Daemon.h, Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/WebCommonPage.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/Resource/html/css/main.css, Source/Resource/html/js/checker/cellMediaInfo.js, Source/Resource/html/js/checker/webengine.js, Source/Resource/html/js/checker/webkit.js
=> Select MediaInfo format for MI output

Source/GUI/Qt/WebKitView.cpp
=> Fix drag & drop on recents macOS

Project/GNU/CLI/test/test_mk.sh
- Fix ffmpeg compilation on Linux
- Fix macOS make issue
=> Tests: some fixes

Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/JS_Tree.cpp, Source/Common/JS_Tree.h, Source/Common/Reports.cpp
=> Use MI text output to generate JStree

Source/Common/MediaConchLib.h
=> x Small memory leak

.travis.yml
=> Update dependancies in .travis.yml

Project/GNU/CLI/test/test_mk.sh
=> Fix tests on mac

Project/GNU/mediaconch.spec
=> Fix Tumbleweed build

Source/Common/Core.cpp
=> x wstring_t string

Source/Common/Reports.cpp, Source/Resource/html/js/checker/cellPolicy.js, Source/Resource/html/js/checker/table.js
=> Do not apply policies to attachments

Source/CLI/CLI.cpp, Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/MediaConchLib.cpp, Source/Common/MediaConchLib.h, Source/Daemon/Daemon.cpp, Source/GUI/Qt/mainwindow.cpp
=> Print error if data directory isn't writable

Source/GUI/Qt/commonwebwindow.cpp
=> x Double call to setHtml()

Source/Resource/html/js/checker/table.js
=> x Missing startsWith function on old Qt versions

Project/GNU/mediaconch.spec
=> Make rpm relocatable

.appveyor.yml
=> AppVeyor: Downgrade Qt to 5.6LTS

Project/GNU/mediaconch.spec, Project/Snap/mediaconch-server/snapcraft.yaml
=> RPM spec: Use %global instead of %define

Project/GNU/CLI/AddThisToRoot_CLI_compile.sh, Project/GNU/GUI/AddThisToRoot_GUI_compile.sh, Project/GNU/Server/AddThisToRoot_Server_compile.sh
=> Ignore command line arguments for external dependencies

Project/Mac/Info-ns.plist, Project/Qt/MediaConch.pro
=> Add custom Info.plist for direct distribution

Project/Mac/Make_MC_dmg.sh
=> Generate macOS < 10.13 compatible DMG

Project/GNU/mediaconch.spec
=> Fix Mageia 7

Project/GNU/mediaconch.spec
=> Fix OBS build for CentOS8

Source/Common/Reports.cpp, Source/Common/Reports.h, Source/Resource/html/js/checker/cellImplementation.js
=> Does not validate implementation of attachments

Source/Common/Core.cpp
=> Add /tmp as fallback writable directory on unix

Source/CLI/CLI.cpp
=> CLI: Download policies

Project/GNU/CLI/configure.ac, Project/GNU/Server/configure.ac, Project/Qt/MediaConch.pro
=> Fix include path for bundled libxslt

Source/CLI/CLI.cpp, Source/CLI/CommandLine_Parser.cpp
=> CLI: Print error for missing policies files

Source/CLI/CLI.cpp, Source/CLI/CLI.h, Source/CLI/CommandLine_Parser.cpp, Source/CLI/CommandLine_Parser.h, Source/CLI/Help.cpp
=> CLI: Output reports to file option

.github/workflows/MediaConch_Checks.yml
I hoped that `apt-get update` would not be needed, but it is not the case.
=> apt-get update is needed

.github/workflows/MediaConch_Checks.yml
=> Fix github-actions

Project/GNU/Library/AddThisToRoot_DLL_compile.sh
=> Add build script for the library

Source/GUI/Qt/commonwebwindow.cpp
=> GUI: Fix "same origin policy" errors with webengine

Project/GNU/GUI/AddThisToRoot_GUI_compile.sh, Project/Mac/Make_MC_dmg.sh, Project/Mac/QtWebEngineProcess-ns.entitlements
=> Fix mac GUI build and packaging

Source/Resource/mediaconch-js/MediaConch.js
=> Mediaconch.js: remove debug code

Source/Resource/mediaconch-js/MediaConch.js
=> MediaConch.js: Handle emscripten v2.x MediaInfo module

Project/GNU/CLI/Makefile.am, Project/GNU/Library/Makefile.am, Project/GNU/Server/Makefile.am, Project/MSVC2015/CLI/MediaConch.vcxproj, Project/MSVC2015/GUI/MediaConch_GUI.vcxproj, Project/MSVC2015/Server/MediaConch-Server.vcxproj, Project/MSVC2017/CLI/MediaConch.vcxproj, Project/MSVC2017/GUI/MediaConch_GUI.vcxproj, Project/MSVC2017/Server/MediaConch-Server.vcxproj, Project/MSVC2019/CLI/MediaConch.vcxproj, Project/MSVC2019/GUI/MediaConch_GUI.vcxproj, Project/MSVC2019/Server/MediaConch-Server.vcxproj, Project/Qt/MediaConch.pro, Source/CLI/CLI.cpp, Source/CLI/CLI.h, Source/CLI/CommandLine_Parser.cpp, Source/CLI/CommandLine_Parser.h, Source/CLI/Help.cpp, Source/Checker/Checker.cpp, Source/Checker/Checker.h, Source/Checker/Makefile.emscripten, Source/Common/Policies.cpp, Source/Common/Policies.h, Source/Common/Reports.cpp, Source/Common/Reports.h, Source/Resource/mediaconch-js/HowToUse.html, Source/Resource/mediaconch-js/MediaConch.js, Source/ThirdParty/tfsxml/tfsxml.c, Source/ThirdParty/tfsxml/tfsxml.h
=> Add --full options for policies

Source/Checker/Checker.cpp, Source/Checker/Checker.h, Source/ThirdParty/tfsxml/tfsxml.c, Source/ThirdParty/tfsxml/tfsxml.h
=> Fix XML parsing in policy checker

Source/Lib/MediaConchLib.py
=> Fix reports format "enum" in python API

Source/Checker/Checker.cpp
=> Use new policy parser for policies with TimeCode* fields

Source/Common/Core.cpp, Source/Common/Core.h, Source/Common/DaemonClient.cpp, Source/Common/DatabaseReport.h, Source/Common/FileRegistered.h, Source/Common/MediaConchLib.cpp, Source/Common/MediaConchLib.h, Source/Common/NoDatabaseReport.cpp, Source/Common/NoDatabaseReport.h, Source/Common/REST_API.cpp, Source/Common/REST_API.h, Source/Common/SQLLite.cpp, Source/Common/SQLLite.h, Source/Common/SQLLiteReport.cpp, Source/Common/SQLLiteReport.h, Source/Daemon/Daemon.cpp, Source/GUI/Qt/DatabaseUi.cpp, Source/GUI/Qt/DatabaseUi.h, Source/GUI/Qt/SQLLiteUi.cpp, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/workerfiles.cpp
=> Do not use outdated checker results

Source/Common/XsltPolicy.cpp, Source/Common/XsltPolicy.h
=> Add extra fields when creating a policy

Project/GNU/CLI/Makefile.am, Project/GNU/Library/Makefile.am, Project/GNU/Server/Makefile.am, Project/MSVC2015/CLI/MediaConch.vcxproj, Project/MSVC2015/GUI/MediaConch_GUI.vcxproj, Project/MSVC2015/Server/MediaConch-Server.vcxproj, Project/MSVC2017/CLI/MediaConch.vcxproj, Project/MSVC2017/GUI/MediaConch_GUI.vcxproj, Project/MSVC2017/Server/MediaConch-Server.vcxproj, Project/MSVC2019/CLI/MediaConch.vcxproj, Project/MSVC2019/GUI/MediaConch_GUI.vcxproj, Project/MSVC2019/Server/MediaConch-Server.vcxproj, Project/Qt/MediaConch.pro, Source/Common/IMSC1.cpp, Source/Common/IMSC1.h, Source/IMSC1/IMSC1Plugin.cpp, Source/IMSC1/IMSC1Plugin.h, Source/IMSC1/Makefile.emscripten, Source/Resource/mediaconch-js/HowToUse.html, Source/Resource/mediaconch-js/MediaConch.js
=> IMSC1 implementation checker js module

Project/GNU/CLI/Makefile.am, Project/GNU/Library/Makefile.am, Project/GNU/Server/Makefile.am, Project/MSVC2015/CLI/MediaConch.vcxproj, Project/MSVC2015/GUI/MediaConch_GUI.vcxproj, Project/MSVC2015/Server/MediaConch-Server.vcxproj, Project/MSVC2017/CLI/MediaConch.vcxproj, Project/MSVC2017/GUI/MediaConch_GUI.vcxproj, Project/MSVC2017/Server/MediaConch-Server.vcxproj, Project/MSVC2019/CLI/MediaConch.vcxproj, Project/MSVC2019/GUI/MediaConch_GUI.vcxproj, Project/MSVC2019/Server/MediaConch-Server.vcxproj, Project/Qt/MediaConch.pro, Source/Checker/Checker.cpp, Source/Checker/Checker.h, Source/Checker/Makefile.emscripten, Source/Checker/Path.cpp, Source/Checker/Path.h
=> Parse extra fields in policy checker

Source/Common/XsltPolicy.cpp
=> Exclude Count and CodecID_Url when creating a policy

Source/Checker/Checker.cpp
=> Fix track indexing in policy checker

Source/Checker/Checker.cpp, Source/Checker/Path.cpp, Source/Checker/Path.h
=> Fix occurrence matching

Source/Resource/mediaconch-js/HowToUse.html, Source/Resource/mediaconch-js/MediaConch.js
=> Add "by buffer" API to MediaConch JavaScript

Source/Checker/Checker.cpp, Source/Checker/Checker.h
=> Show first failing value in rule's 'actual' attribute

Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/WebCommonPage.h, Source/Resource/html/formOnline.html, Source/Resource/html/formRepository.html, Source/Resource/html/formUpload.html, Source/Resource/html/js/checker/base.js
=> GUI: Support custom parse speed option

Project/GNU/CLI/test/test_mk.sh, Source/Resource/html/formOnline.html, Source/Resource/html/formRepository.html, Source/Resource/html/js/checker/webengine.js, Source/Resource/html/js/checker/webkit.js
=> GUI: Fix setting parse speed from js

Source/Checker/Checker.cpp
=> Fix misuse of std::all_of in policy checker

Source/Checker/Checker.cpp, Source/Checker/Checker.h, Source/Common/Reports.cpp
Fix https://github.com/MediaArea/MediaConch/issues/232.
=> Use xslt policy checker for 'mmt' and 'compare' features

Source/GUI/Qt/DatabaseUi.cpp, Source/GUI/Qt/DatabaseUi.h, Source/GUI/Qt/NoDatabaseUi.cpp, Source/GUI/Qt/NoDatabaseUi.h, Source/GUI/Qt/SQLLiteUi.cpp, Source/GUI/Qt/SQLLiteUi.h, Source/GUI/Qt/WebCommonPage.cpp, Source/GUI/Qt/WebCommonPage.h, Source/GUI/Qt/checkerwindow.cpp, Source/GUI/Qt/checkerwindow.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.h, Source/GUI/Qt/settingswindow.cpp, Source/GUI/Qt/settingswindow.h, Source/GUI/Qt/uisettings.cpp, Source/GUI/Qt/uisettings.h, Source/Resource/html/formOnline.html, Source/Resource/html/formRepository.html, Source/Resource/html/formUpload.html, Source/Resource/html/js/checker/base.js, Source/Resource/html/js/checker/webengine.js, Source/Resource/html/js/checker/webkit.js, Source/Resource/html/js/settings.js, Source/Resource/html/settings.html
=> GUI: Add parsespeed option to settings page

Source/Common/Policy.cpp
=> Fix warning in Policy copy constructor

.github/workflows/MediaConch_Checks.yml, Source/Checker/Checker.cpp
=> checker: Fix behavior when operator attribute is missing

Project/GNU/mediaconch.spec
=> Fix spec for rhel 9 based distributions

Source/CLI/Help.cpp, Source/Checker/Checker.cpp, Source/Common/Reports.cpp, Source/Common/Version.h, Source/Daemon/Daemon.cpp, Source/GUI/Qt/mainwindow.cpp, Source/IMSC1/IMSC1Plugin.cpp
Sample output:
```
<MediaConch xmlns="https://mediaarea.net/mediaconch" xmlns:mmt="https://mediaarea.net/micromediatrace" xmlns:mi="https://mediaarea.net/mediainfo" version="0.3">
<creatingApplication version="23.07.20230720" url="https://mediaarea.net/MediaConch">MediaConch</creatingApplication>
<creatingLibrary version="23.07.20230720" url="https://mediaarea.net/MediaInfo">MediaInfoLib</creatingLibrary>
<media ref="...">
...
</media>
</MediaConch>
```
=> Add creatingApplication information to output xml

Source/Checker/Checker.cpp, Source/Checker/Checker.h, Source/Resource/html/Help/How To Use/How To Use.html, Source/Resource/html/js/policy.js, Source/Resource/html/js/policyTreeRulesMI.js, Source/Resource/html/xslPolicy.html
+ Update GUI and help
Fixes #764
=> Handle occurence field for exists and must not exists validators

Source/Checker/Checker.cpp
=> Fix missing is_not_equal validator in Checker.cpp

Tools/Policies/sample_policy_4_mkv_ffv1_digitization.xml
fixes https://github.com/amiaopensource/vrecord/issues/857
=> Tweak aspect ratio in mkv policy

Source/GUI/Qt/settingswindow.cpp
=> Fix Qt6 compatibility
