MediaArea/MediaConch_SourceCode

Source/Common/Policies.cpp

Libxml2 already encodes the character ('>' and '<') to HTML code.

Policies: No need to use HTML character for validator

---

Source/Common/JS_Tree.cpp

JS-Tree: do not print hexa values if not numerical

---

Source/GUI/Qt/displaymenu.ui

GUI: rename the qgridlayout to avoid duplicate name

---

Source/Common/DpfManager.cpp

Plugins/DPF: use absolute path on !Win32

---

Source/GUI/Qt/workerfiles.cpp

GUI: the reort kind is not saved, reupdate before printing

---

Source/Resource/displays/MediaConchHtml.xsl

Related to #273 this adds toggle ability. Right now it's on/off for *everything* but I hope to later make that item-level instead. This also upgrades the display to reflect @dericed's changes in the XML structure for the implementation checker. Jerome, please review!

toggles verbose view, updates to v0.2 of implementation checker XSL

---

Source/Resource/displays/MediaConchHtml.xsl

This reduces one validation error, by declaring what kind of script in the embedded CSS.

declares script type as CSS

---

Source/Common/Core.cpp

update for better supporting old versions of MediaInfoLib

XSL: use or not the https

---

Source/GUI/Qt/WebEnginePage.cpp
Source/GUI/Qt/WebKitPage.cpp

GUI: Use UTF-8 and not local when saving report

---

Project/GNU/mediaconch.spec

Use Qt5WebEngine instead of Qt5WebKit for Fedora >= 24

---

Source/Common/Core.cpp
Source/Common/Core.h

Use a dedicated feature of MediaInfoLib, fallback on the previous method if MediaInfoLib version does not support the feature.

Avoid 2 internal memory copies of the trace

---

Project/GNU/mediaconch.spec

- CentOS 5/RHEL 5 (CLI only, no sqlite)
- CentOS 6/RHEL 6/RHEL 7 (CLI only)
- CentOS 7 (CLI and server)
- SLE 11/OpenSUSE 11 (CLI only)
- Mageia 5 (CLI, GUI and server)

Add distributions to spec file

---

Source/Resource/displays/MediaConchHtml.xsl
Tools/Transforms/verapdf2mediaconch.xsl

cc @ablwr. the ‘xsl:if’ only let out one context, I changed to a ‘xsl:for-each’ loop to let them all out. didn’t check if the same logic is needed in the text versions.

Report many contexts

---

Project/Qt/MediaConch.pro

QMAKE_CXXFLAGS  aren't passed to C preprocessor by moc, making impossible to use webkit with Qt5.6+

QMake: replaces CXXFLAGS by DEFINES in MediaConch.pro

---

Project/GNU/CLI/AddThisToRoot_CLI_compile.sh
Project/GNU/GUI/AddThisToRoot_GUI_compile.sh
Project/GNU/Server/AddThisToRoot_Server_compile.sh
Source/Common/Plugin.cpp

- MacOS libc don't provide execvpe
- execvp seem sufficient for passing unmodified environment
- Fix build scripts

Fix MacOS build

---

Source/Common/generated/GeneratedCSVVideos.h

Policy Editor uses Version fields from MediaInfo report, but for new XML we decided to remove "Version " from the Version field, so manually removing "Version " from the list.
@tribouille at long term there is a need to handle this specific case in the list creation tool.

Version in Policy Editor

---

Source/GUI/Qt/WebCommonPage.cpp
Source/GUI/Qt/mainwindow.cpp

Fix: https://github.com/MediaArea/MediaConch/issues/161

GUI: truncate when saving a policy to a file

---

Source/Common/Policies.cpp
Source/Common/Policies.h
Source/Common/Policy.cpp
Source/Common/Policy.h
Source/Common/XsltPolicy.cpp

Policy: do not set the isPublic policy when exporting policy

---

Tools/Policies/policyset2policytransform2policyresult.xsl

for instance allows:
`m:moov/m:trak/m:mdia/m:minf/m:stbl/m:stsd/Video/m:pasp`
as an alternate to
`File header/Track/Media/Media Information/Sample Table/Sample
Description/Video/Pixel Nope/Header/Name`
to optimize path references in mov, avi, etc

allow mmt rule to reference elemental names

---

Source/Common/Queue.cpp
Source/Common/Queue.h
Source/Common/Scheduler.cpp

Uses a new option in MediaInfoLib, up to date version is requested.

Completely stop the parsing when remove is requested from the UI.

---

Source/Common/Scheduler.h

TODO: check issues with the GUI when there are tons of files

Disable default multi-thread

---

Source/CLI/CLI.cpp

Return non-zero exit code when unable to create output file

---

Source/Checker/Checker.cpp

`_Total` is not stored in default report and need to be computed before applying a policy
Needed for https://github.com/MediaArea/MediaInfoLib/pull/1783.

Force full report if '_Total' is in a policy

---

Source/Common/XsltPolicy.cpp

Can still be created manually, but creating corresponding policy rules makes a huge list by default.

Creation of rule from a media skips "/String" fields

---

Source/CLI/CLI.cpp
Source/CLI/CLI.h
Source/GUI/Qt/mainwindow.cpp
Source/Resource/html/js/checker/base.js

Force ParseSpeed to 1 when fixer

---

Source/CLI/CLI.cpp
Source/CLI/CLI.h
Source/CLI/CommandLine_Parser.cpp
Source/CLI/CommandLine_Parser.h
Source/CLI/Help.cpp
Source/GUI/Qt/WebCommonPage.cpp
Source/GUI/Qt/WebCommonPage.h
Source/Resource/html/formRepository.html
Source/Resource/html/js/checker/webengine.js
Source/Resource/html/js/checker/webkit.js

CLI: --IncludeHidden (restore previous version behavior)
GUI: Checkbox option
Fixes https://github.com/MediaArea/MediaConch_SourceCode/issues/785.

Add option to include hidden files when adding folder

---

Source/CLI/CLI.cpp
Source/CLI/CLI.h
Source/CLI/CommandLine_Parser.cpp
Source/CLI/CommandLine_Parser.h
Source/CLI/Help.cpp
Source/Common/Core.cpp
Source/Common/Core.h
Source/Common/MediaConchLib.cpp
Source/Common/MediaConchLib.h

CLI: Add option to disable use of the database

---

Source/CLI/CLI.cpp
Source/Checker/Checker.cpp
Source/Checker/Checker.h
Source/Checker/Path.cpp
Source/Common/Core.cpp
Source/Common/Policy.cpp
Source/Common/Scheduler.cpp
Source/Common/Scheduler.h
Source/Common/Xslt.cpp
Source/IMSC1/IMSC1Plugin.cpp

And fix some compilers warnings
Fixes #719

Remove / replace use of deprecated libxml2 functions

---

Source/Checker/Checker.cpp

Always Use C style double conversion
